Repository Automattic/block-experiments, pull requests merged in 2021-07, with the labels that each got.

#219 Address block discoverability issues in Bauhaus Centenary Block
  bundler/bundles/bauhaus-centenary.json
  bundler/resources/a8c-bauhaus-centenary/block.json
  bundler/resources/a8c-bauhaus-centenary/readme.txt
Labels: enhancement

#220 Address block discoverability issues in Waves Block
  bundler/bundles/waves.json
  bundler/resources/a8c-waves/block.json
  bundler/resources/a8c-waves/readme.txt
Labels: enhancement

#221 Address block discoverability issues in Starscape Block
  bundler/bundles/starscape.json
  bundler/resources/a8c-starscape/block.json
  bundler/resources/a8c-starscape/readme.txt
Labels: enhancement

#223 Update dependency perfect-freehand to 0.4.91 for Sketch block
  bundler/bundles/sketch.json
  bundler/resources/a8c-sketch/readme.txt
  package.json
  yarn.lock
Labels: bug, enhancement

#224 Revert "Update dependency perfect-freehand to 0.4.91 for Sketch block"
  bundler/bundles/sketch.json
  bundler/resources/a8c-sketch/readme.txt
  package.json
  yarn.lock
Labels: bug

#225 Update dependency perfect-freehand to 0.4.91 for Sketch block (Second take)
  blocks/sketch/src/edit.js
  blocks/sketch/src/lib.js
  bundler/bundles/sketch.json
  bundler/resources/a8c-sketch/readme.txt
  package.json
  yarn.lock
Labels: [Satus] In Progress

#226 Layout Grid: Correctly align image block with right alignment
  blocks/layout-grid/editor.scss
Labels: bug

#233 Fix styling for center-aligned events
  blocks/event/editor.scss
  blocks/event/style.scss
  bundler/bundles/event.json
  bundler/resources/a8c-event/block.json
  bundler/resources/a8c-event/readme.txt
Labels: bug
